// All routes to precache on app startup for offline use
// Dynamic routes ([id]) are excluded — they get cached when viewed
// or their data is available from IndexedDB

export const PRECACHE_ROUTES = [
  '/',
  '/incidents',
  '/encounters',
  '/encounters/new',
  '/encounters/new/simple',
  '/encounters/new/pcr',
  '/encounters/photos/new',
  '/encounters/procedures/new',
  '/mar',
  '/mar/new',
  '/units',
  '/units/new',
  '/cs',
  '/cs/count',
  '/cs/checklist',
  '/cs/receive',
  '/cs/transfer',
  '/cs/audit',
  '/supply-runs',
  '/supply-runs/new',
  '/inventory',
  '/inventory/add',
  '/inventory/burnrate',
  '/inventory/reorder',
  '/roster',
  '/roster/hr',
  '/roster/new',
  '/schedule',
  '/schedule/calendar',
  '/schedule/generate',
  '/contacts',
  '/documents',
  '/documents/handbook',
  '/documents/new',
  '/formulary',
  '/ics214',
  '/ics214/new',
  '/analytics',
  '/profile',
  '/payroll',
  '/payroll/my',
  '/billing',
  '/comp-claims',
  '/comp-claims/new',
  '/consent/ama',
  '/unsigned-orders',
  '/dashboard/my-unit',
  '/admin',
  '/admin/company',
  '/admin/chat-requests',
  '/admin/announcements',
  '/admin/fire-dashboard',
]
